version: "3.9"
services:
  db:
    image: postgres:15
    container_name: postgres_db_ssmif
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ssmif
    ports:
      - "5432:5432"
    volumes:
      - ssmif_db:/var/lib/postgresql/data
  app:
    build: ./src
    restart: always
    ports:
        - 8080:8080
    environment:
        - PUID=1000 # change this to your user id
        - PGID=1000 # change this to your group id
    volumes:
        - ./src:/app/


volumes:
  ssmif_db: