# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "backtrader" = super.buildPythonPackage rec {
    pname = "backtrader";
    version = "1.9.78.123";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f3/ef/328c6ec332435f63b3e18febd263686b8ba07e990676a862cc8522ba38f5/backtrader-1.9.78.123-py2.py3-none-any.whl";
      sha256 = "1zaxkldkxs4m0jrkfg8b0bbiswfq0ja6xi9mk99mb4fyn0baa1ws";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
